name: Build and Test React Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  confirm-main-branch:
    name: Confirm release is run on public/main branch
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Branch name
        run: |
          BRANCHNAME=${GITHUB_REF##*/}
          echo "confirming branch name, branch name is:"
          echo $BRANCHNAME
          if [ $BRANCHNAME != "main" ]
          then
            echo "You can only run a release from the main branch, you are trying to run it from ${BRANCHNAME}"
            exit 1
          fi

  build:
    name: Deploy Core SDK Sample Apps to Github Pages
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: Justin Avioli
      GIT_AUTHOR_EMAIL: justin.avioli@gmail.com
      GIT_COMMITTER_NAME: Justin Avioli
      GIT_COMMITTER_EMAIL: justin.avioli@gmail.com

    strategy:
      matrix:
        apps: [holy-shirts-and-pants] 

    steps:
    - name: Use Node.js to build and test ${{ matrix.apps }}
      uses: actions/checkout@v3
      with:
        node-version: 16.x
        cache: 'npm'
        
    - name : Install Dependencies
      working-directory: core-sdk-samples/${{ matrix.apps }}
      run: |
          npm ci
          npm run build
      
    - name: Deploy to Github Pages
      working-directory: core-sdk-samples/${{ matrix.apps }}
      run: |
          git remote set-url origin https://git:${GITHUB_REPOSITORY_OWNER}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
