name: Build and Test React Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
      working-directory: core-sdk-samples/

jobs:

  confirm-main-branch:
    name: Confirm release is run on public/main branch
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Branch name
        run: |
          BRANCHNAME=${GITHUB_REF##*/}
          echo "confirming branch name, branch name is:"
          echo $BRANCHNAME
          if [ $BRANCHNAME != "main" ]
          then
            echo "You can only run a release from the main branch, you are trying to run it from ${BRANCHNAME}"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        apps: [holy-shirts-and-pants, higgs-shop-sample-app]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js to build and test ${{ matrix.apps }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        
    - name : Change Directory
      run: cd ${{ matrix.apps }}/
        
    - name : Install Dependencies
      run: npm ci
      
    - name: Deploy to Github Pages
      run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
      env:
          GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
